version: "3.9"
# python manage.py createsuperuser:

services:
  db:
    image: mysql:8.0
    container_name: forceforge-db
    restart: always
    environment:
      MYSQL_DATABASE: focusforge_db
      MYSQL_USER: focusforge_admin
      MYSQL_PASSWORD: Amir@li3902
      MYSQL_ROOT_PASSWORD: Amir@li3902
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    container_name: forceforge-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]

volumes:
  mysql_data:
